import type { Metadata } from "next";
import { Fraunces, Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});
const fraunces = Fraunces({
	subsets: ["latin"],
	variable: "--font-serif",
});

export const metadata: Metadata = {
	title: "Frog Caffe Bar",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${fraunces.variable} ${quicksand.className}`}>
				{children}
			</body>
		</html>
	);
}
